### ISSUE TITLE
Uploading files with Multer

### ISSUE THREAD

**Issue by jferrettiboke** [apollographql/graphql-server#301]
Hi everyone!

I am trying to uploading files with Multer through GraphQL. There are two ways to go.

1. Uploading files in a single no-GraphQL endpoint or using Multer like Express middleware.
2. Uploading files using Multer inside a specific GraphQL resolver function.

For the first approach any file can be uploaded using `.any()` (Multer), which is fast but it is not possible to make specific validation rules for each GraphQL resource.
For the second approach is totally valid make validation rules, which is more flexible.

Once explained this, I am interested to achieve the second approach. I think it is almost done but I am getting errors.

**Test output.**

```
Uncaught SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>)
```

I am getting this error because the server is not returning text in the response. `res.text` is undefined on `expect(JSON.parse(res.text)).to.deep.equal(...)`.

**Server output.**

```
TypeError: Cannot read property 'definitions' of undefined
    at buildExecutionContext (\Projects\graphql-express-multer-example\node_modules\graphql\execution\execute.js:162:11)
    at Object.execute (\Projects\graphql-express-multer-example\node_modules\graphql\execution\execute.js:109:17)
    at doRunQuery (\Projects\graphql-express-multer-example\node_modules\graphql-server-core\dist\runQuery.js:77:26)
    at resolvedPromise.then (\Projects\graphql-express-multer-example\node_modules\graphql-server-core\dist\runQuery.js:18:39)
```

You can see and check the repository [here](https://github.com/jferrettiboke/graphql-express-multer-example). Feel free to send a PR or create a issue there.

Maybe something related with Apollo Server? Any thoughts on this?

Thanks in advance.

```js
// server.js

const express = require('express');
const bodyParser = require('body-parser');
const multer = require('multer');
const { graphqlExpress, graphiqlExpress } = require('graphql-server-express');
const schema = require('./schema');

const PORT = 3000;
const app = express();

app.use('/graphql', bodyParser.json(), graphqlExpress(request => ({
  schema,
  context: { request },
  formatError: err => { console.log(err.stack); return err; }
})));

app.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql',
}));

const server = app.listen(PORT);
```

```js
// schema.js

const multer = require('multer');
const { makeExecutableSchema } = require('graphql-tools');

const typeDefs = [/* GraphQL */`
  type UserPhoto {
    name: String
    extension: String
  }

  type Query {
    hello: String
  }

  type Mutation {
    uploadUserPhoto: UserPhoto
  }

  schema {
    query: Query
    mutation: Mutation
  }
`];

const resolvers = {
  Query: {
    hello() {
      return 'Hello World!';
    }
  },
  Mutation: {
    uploadUserPhoto(root, args, context) {
      const storage = multer.diskStorage({
        destination: function (req, file, callback) {
          callback(null, './uploads');
        },
        filename: function (req, file, callback) {
          callback(null, Date.now() + '-' + file.originalname);
        }
      });

      const upload = multer({ storage }).single('userPhoto');

      return upload(context.request, {}, (err) => {
        if (err) {
          throw err;
        }

        console.log({
          query: context.request.query,
          body: context.request.body,
          file: context.request.file,
          files: context.request.files
        });

        return {
          name: 'success.jpg',
          extension: 'jpg'
        };
      });
    }
  }
};

module.exports = makeExecutableSchema({ typeDefs, resolvers });
```

```js
// graphql.test.js

const fs = require('fs');
const { describe, it } = require('mocha');
const { expect } = require('chai');
const request = require('request');

describe('GraphQL', () => {
  describe('Mutation', () => {
    it('uploadUserPhoto on /graphql endpoint (THIS DOES NOT WORK)', done => {
      const query = `
        mutation uploadUserPhoto {
          name
          extension
        }
      `;

      const data = {
        qs: {
          query
        },
        formData: {
          userPhoto: fs.createReadStream(__filename)
        }
      };

      request.post('http://localhost:3000/graphql', data, (err, res, body) => {
        if (err) {
          return done(err);
        }
        
        console.log('Upload successful!  Server responded with:', body);

        expect(JSON.parse(res.text)).to.deep.equal({
          data: {
            uploadUserPhoto: {
              name: 'success.jpg',
              extension: 'jpg'
            }
          }
        });
        done();
      });
    });
  });
});
```

**Comment by smolinari** [comment]
Have you seen this?

https://github.com/jangerhofer/apolloFileUpload/blob/master/server/main.js

Also, are you using apollo-client? If you are, have a look at [this issue](https://github.com/apollographql/apollo/issues/65). 

Scott

**Comment by jferrettiboke** [comment]
Thanks @smolinari.

Note in the code that I would like to use Multer inside GraphQL resolve functions, not using a single endpoint or middleware before calling `graphqlExpress()`. The example you gave me is using Multer like a Express middleware before calling GraphQL.
I think my approach is worth because I do not miss the validation rules with Multer, so I can set different validation rules depending of the resource.

Thanks for the issue! I did not know about it.

**Comment by jaydenseric** [comment]
@jferrettiboke did you get it to work in the end?

**Comment by jferrettiboke** [comment]
Hi @jaydenseric. No, yet. Do you have some ideas?

**Comment by jaydenseric** [comment]
Yea, I'll try to get everything working and publish it sometime soon.

**Comment by helfer** [comment]
Closing this for lack of activity. Let's keep track of file upload related things in #229. If anyone has time to write up and propose a design, I'd be more than happy to review it. Any and all contributions, big or small are welcome!

**Comment by jaydenseric** [comment]
For an immediate solution, checkout [apollo-upload-server](https://github.com/jaydenseric/apollo-upload-server).
