### ISSUE TITLE
[express] cannot get example running because of typescript error?

### ISSUE THREAD

**Issue by divramod** [apollographql/graphql-server#358]
Hey, i try to get the express example running with the following code:

index.ts

```
import * as express from 'express';
import bodyParser from 'body-parser';
import { graphqlExpress } from 'graphql-server-express';
import * as mySchema from './schema';

const PORT = 3002;
var app = express();

// bodyParser is needed just for POST.
app.use('/graphql', bodyParser.json(), graphqlExpress({ schema: mySchema }));

app.listen(PORT);
```

schema.ts

```
export default `
type Author {
  id: Int! # the ! means that every author object _must_ have an id
  firstName: String
  lastName: String
  posts: [Post] # the list of Posts by this author
}

type Post {
  id: Int!
  title: String
  votes: Int
  author: Author
}

# the schema allows the following query:
type Query {
  posts: [Post]
  author(id: Int!): Author # author query must receive an id as argument
}

# this schema allows the following mutation:
type Mutation {
  upvotePost (
    postId: Int!
  ): Post
}

# we need to tell the server which types represent the root query
# and root mutation types. We call them RootQuery and RootMutation by convention.
schema {
  query: Query
  mutation: Mutation
}
`;
```

package.json
```
{
  "name": "express",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node_modules/.bin/nodemon dist/index.js",
    "compile": "node_modules/.bin/gulp compile",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.17.1",
    "express": "^4.15.2",
    "graphql": "^0.9.2",
    "graphql-server-express": "^0.7.0"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-typescript": "^3.1.1",
    "nodemon": "^1.11.0",
    "typed-graphql": "^1.0.2",
    "typescript": "^2.2.2"
  }
}
```

i got this error message:
```
api/express/dist/index.js:11
app.use('/graphql', body_parser_1.default.json(), graphql_server_express_1.graphqlExpress({ schema: mySchema }));
                                         ^

TypeError: Cannot read property 'json' of undefined
    at Object.<anonymous> (/home/mod/_me/code/projects/api/express/dist/index.js:11:42)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

i have a similar setup with the hapi example and got it running. some idea on what i am doing wrong?

**Comment by helfer** [comment]
Your bodyParser import doesn't seem to do what you wanted. This is unlikely to be an issue with graphql-server, so I'll close this. Please feel free to ask for help on SO or the slack channel!
